---
title: "Scatterplots"
author: "Sali Mahdy"
date: '2022-04-26'
output: html_document
---

```{r}
library(readxl)
library(readr)
library(tidyverse)
library(ggplot2)
library(ggalt)
library(dplyr)
library(ggmap)
library(rgdal)
library(sp)
library(sf)
library(ggthemes)
library(leaflet)
library(geojsonio)
library(broom)
library(leafsync)
library(RColorBrewer)
library(DT)
library(magick)
library(knitr)
library(devtools)
library(plotly)
library(MetBrewer)

```

```{r}
china<-read.csv('AidDatasGlobalChineseDevelopmentFinanceDataset_v2.0.csv')
china_military<-read.csv('MilitaryAidDatasGlobalChineseDevelopmentFinanceDataset_v2.0.csv')
china_invs<-read.csv('China-Global-Investment-Tracker-2021-Fall-FINAL-2022.2.21-update.up.csv')
```

```{r}
c_inv<-china_invs%>%
  select(Region, Year, Quantity.in.Millions, Country)%>%
  filter(Region==c('Sub-Saharan Africa', 'Arab Middle East and North Africa'))%>%
  group_by(Year, Region)%>%
  mutate(af_total=sum(as.numeric(gsub("[[:punct:]]", "", Quantity.in.Millions))))




tot_reg<-china_invs%>%
  select(Region, Year, Quantity.in.Millions)%>%
  group_by(Year, Region)%>%
  mutate(reg_total=sum(as.numeric(gsub("[[:punct:]]", "", Quantity.in.Millions))))
```


```{r}

c<-ggplot(c_inv, aes(x=Year, y=af_total/100, color=Region))+
  geom_line()+
  geom_point()+
  labs(x='Year', y='Aid in Billions ($)', title='Chinese Aid to Africa and Middle East, 2005-2021')+
  scale_color_manual(values=c('Red', 'Yellow'))+
  theme(
  panel.border = element_blank(),  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.title = element_text(hjust = 0.5)
  )

#by region facet
r<-ggplot(tot_reg, aes(x=Year, y=reg_total/100, color=Region))+
  geom_line()+
  geom_point()+
  labs(x='Year', y='Aid in Billions ($)', title='Chinese Aid by Region, 2005-2021')+
  theme(
  panel.border = element_blank(),  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.title = element_text(hjust = 0.5), 
  legend.position = 'none'
  )+
  facet_wrap(vars(Region))+
  scale_color_manual(values=met.brewer("Renoir", n=9, type='continuous'))
  
```

```{r}
ggplotly(c)
```

```{r}
ggplotly(r)
```

```{r}
sec<-china_invs%>%
  select(Region, Sector, Year)%>%
  group_by(Sector)%>%
  summarize(frequency=n())
```

```{r}
ggplot(sec, aes(x=Sector, y=frequency, fill=Sector))+ 
  geom_bar(stat='identity')+
  coord_flip()+
  theme_bw()+
  guides(fill=F)+
  labs(title='Chinese Investment by Sector', y='Total Number of Projects', x='')+
  scale_fill_manual(values=met.brewer("Renoir", n=14, type='continuous'))+
 theme(
  panel.border = element_blank(),  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.title = element_text(hjust = 0.5), 
  legend.position = 'none'
  )
```


