---
title: "Untitled"
author: "John Marion"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(vdemdata)
f<-vdem
f<-rename(f,Country=country_name)
f$year<-as.numeric(f$year)
f<-filter(f, year>1990)

chn_inv<-read.csv('China-Global-Investment-Tracker-2021-Fall-FINAL-2022.2.21-update.up.csv')
```

```{r}
f$v2x_egaldem<-as.numeric(f$v2x_egaldem)
f<-f %>%
  group_by(Country) %>%
  mutate(dem_std = (v2x_egaldem-mean(v2x_egaldem, na.rm=T))/sd(v2x_egaldem))
```

```{r}
chn_inv<-chn_inv %>%
  group_by(Year, Country) %>%
  mutate(inv_tot = sum(as.numeric(gsub("[[:punct:]]", "", Quantity.in.Millions))))
```

```{r}
chn_inv[chn_inv$Country=="USA",]$Country<-"United States of America"
chn_inv[chn_inv$Country=="Russian Federation",]$Country<-"Russia"
chn_inv[chn_inv$Country=="Britain",]$Country<-"United Kingdom"
chn_inv[chn_inv$Country=="Trinidad-Tobago",]$Country<-"Trinidad and Tobago"
chn_inv[chn_inv$Country=="Congo",]$Country<-"Republic of the Congo"
chn_inv[chn_inv$Country=="UAE",]$Country<-"United Arab Emirates"
chn_inv[chn_inv$Country=="Sao Tome",]$Country<-"Sao Tome and Principe"
chn_inv[chn_inv$Country=="Bosnia",]$Country<-"Bosnia and Herzegovina"
chn_inv[chn_inv$Country=="Macedonia",]$Country<-"North Macedonia"

f[f$Country=="Burma/Myanmar",]$Country<-"Myanmar"
```

```{r}
ggplot(inner_join(f, chn_inv,by="Country"), aes(x=log(inv_tot), y=dem_std))+
  geom_point(alpha=.01)+
  geom_smooth(method="lm")
```

```{r}
chn_inv<-chn_inv %>%
  group_by(Year) %>%
  mutate(ann_tot = sum(inv_tot))

ggplot(chn_inv[!duplicated(chn_inv$Year),])+
  geom_line(aes(x=Year,y=ann_tot))+
  geom_vline(xintercept = 2016, linetype="dotted",alpha=.5, color="blue")+
  theme_classic()
```

```{r}
imf<-na_if(rename(read.csv('WB_Data/5351a96d-1d86-4c24-875e-52732e298e43_Data.csv'),name=ï..Country.Name, year=Time, IMF_cred=Use.of.IMF.credit..DOD..current.US....DT.DOD.DIMF.CD., Net_Flows_con=Net.financial.flows..IMF.concessional..NFL..current.US....DT.NFL.IMFC.CD., Net_Flows_non=Net.financial.flows..IMF.nonconcessional..NFL..current.US....DT.NFL.IMFN.CD., repurch_charg=IMF.repurchases.and.charges..TDS..current.US....DT.TDS.DIMF.CD.)[1:6727,c(1,3,5:8)], "..")

imf[imf$name=="Cote d'Ivoire",]$name<-"Ivory Coast"
imf[imf$name=="Congo, Rep.",]$name<-"Republic of Congo"
imf[imf$name=="Congo, Dem. Rep.",]$name<-"Democratic Republic of the Congo"
imf[imf$name=="Egypt, Arab Rep.",]$name<-"Egypt"
imf[imf$name=="Iran, Islamic Rep.",]$name<-"Iran"
imf[imf$name=="Korea, Rep.",]$name<-"South Korea"
imf[imf$name=="Korea, Dem. People's Rep.",]$name<-"North Korea"
imf[imf$name=="Kyrgyz Republic",]$name<-"Kyrgzstan"
imf[imf$name=="Lao PDR",]$name<-"Laos"
imf[imf$name=="Micronesia, Fed. Sts.",]$name<-"Micronesia"
imf[imf$name=="Syrian Arab Republic",]$name<-"Syria"
imf[imf$name=="Gambia, The",]$name<-"Gambia"
imf[imf$name=="Russian Federation",]$name<-"Russia"
imf[imf$name=="United States",]$name<-"USA"
imf[imf$name=="St. Lucia",]$name<-"Saint Lucia"
imf[imf$name=="Yemen, Rep.",]$name<-"Yemen"
imf[imf$name=="Bahamas, The",]$name<-"Bahamas"
imf[imf$name=="Brunei Darussalam",]$name<-"Brunei"
imf[imf$name=="Cabo Verde",]$name<-"Cape Verde"
imf[imf$name=="United Kingdom",]$name<-"UK"
imf[imf$name=="Venezuela, RB",]$name<-"Venezuela"
imf[imf$name=="Slovak Republic",]$name<-"Slovakia"
imf[imf$name=="Hong Kong SAR, China",]$name<-"Hong Kong"
imf[imf$name=="Bahamas",]$name<-"Bahamas"

imf<-imf %>%
  group_by(year) %>%
  mutate(ann_imf=sum(as.numeric(IMF_cred),na.rm=T))
```
```{r}
ggplot(imf[!duplicated(imf$year),])+
  geom_line(aes(x=year,y=ann_imf))+
  geom_vline(xintercept=2016, linetype="dotted", color="blue", alpha=.5)
```

```{r}
ggplot()+
  geom_line(data=imf[!duplicated(imf$year),], aes(x=year,y=ann_imf/1000000), color="blue")+
  geom_vline(xintercept=2016, linetype="dotted", alpha=.5)+
  geom_line(data=chn_inv[!duplicated(chn_inv$Year),], aes(x=Year,y=ann_tot), color="red")+
  theme_classic()
```
```{r}
library(MetBrewer)
ggplot()+
  geom_line(data=imf[!duplicated(imf$year),], aes(x=year,y=ann_imf/10000000000), color='blue')+
  geom_vline(xintercept=2016, linetype="dotted", alpha=.5)+
  geom_line(data=chn_inv[!duplicated(chn_inv$Year),], aes(x=Year,y=ann_tot/10000), color='red')+
  labs(x='Year', y='Total Aid in Billions ($)', title='IMF vs. Chinese Aid')+
theme(
  panel.border = element_blank(),  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.title = element_text(hjust = 0.5)
  )
```

```{r}
c<-ggplot()+
  geom_line(data=imf[!duplicated(imf$year),], aes(x=year,y=ann_imf/10000000000, lwd=1), color='dodgerblue4', size=2)+
  labs(x='Year', y='Total Aid in Billions ($)', title='Total IMF Aid, 1990-2020')+
  theme(
  panel.border = element_blank(),  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.title = element_text(hjust = 0.5), 
  legend.position = 'none'
  )
```

```{r}
i<-ggplot()+
  geom_line(data=chn_inv[!duplicated(chn_inv$Year),], aes(x=Year,y=ann_tot/10000), color='darkred', size=2)+
  labs(x='Year', y='Total Aid in Billions ($)', title='Total Chinese Aid, 2005-2021')+
theme(
  panel.border = element_blank(),  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.title = element_text(hjust = 0.5), 
  legend.position = 'none'
  )

```

```{r}
library(patchwork)
c+i
```


